name: Build documentation

on: workflow_call

jobs:
  buildDocs:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up source JDK
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: temurin
      - name: Build developer documentation
        run: mvn clean install -DskipTests -P ci,local -Dexecution.antora.skip=false
      - name: Archive Antora artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Documentation archive
          path: hartshorn-assembly/target/site
          if-no-files-found: error
          retention-days: 7
      - name: Build Javadocs
        run: mvn install -DskipTests -P ci -Dexecution.javadoc.skip=false
      - name: Archive Javadoc artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Documentation archive
          path: hartshorn-assembly/target/site/apidocs
          if-no-files-found: error
          retention-days: 7